# plugin.yml
name: NestedWarps
version: 1.0
main: net.Alexxiconify.warputil.NestedWarpsPlugin
api-version: 1.21 # Ensure this matches your server's Minecraft version
authors: Alexxiconify
description: A Minecraft plugin for nested /warp and /home commands.

permissions:
  nestedwarps.warp:
    description: Allows players to use the /warp command generally.
    default: true
  nestedwarps.warp.*:
    description: Allows players to warp to any specific public warp.
    default: op # Or 'false' if you want to grant specific warps only
  nestedwarps.setwarp:
    description: Allows players to use the /setwarp command.
    default: op
  nestedwarps.delwarp:
    description: Allows players to use the /delwarp command.
    default: op
  nestedwarps.list:
    description: Allows players to use the /warps command.
    default: true
  nestedhomes.home:
    description: Allows players to use the /home command.
    default: true # Players usually have access to their own homes
  nestedhomes.sethome:
    description: Allows players to use the /sethome command.
    default: true
  nestedhomes.delhome:
    description: Allows players to use the /delhome command.
    default: true
  nestedhomes.list:
    description: Allows players to use the /homes command.
    default: true