# plugin.yml
name: NestedWarps
version: 1.0
main: net.Alexxiconify.warputil.NestedWarpsPlugin
api-version: 1.21
authors: Alexxiconify
description: A Minecraft plugin for nested /warp and /home commands, including shared homes.

permissions:
  nestedwarps.warp:
    description: Allows players to use the /warp command generally.
    default: true
  nestedwarps.warp.*:
    description: Allows players to warp to any specific public warp.
    default: op
  nestedwarps.setwarp:
    description: Allows players to use the /setwarp command.
    default: op
  nestedwarps.delwarp:
    description: Allows players to use the /delwarp command.
    default: op
  nestedwarps.list:
    description: Allows players to use the /warps command.
    default: true
  nestedhomes.home:
    description: Allows players to use the /home command (including shared homes).
    default: true
  nestedhomes.sethome:
    description: Allows players to use the /sethome command.
    default: true
  nestedhomes.delhome:
    description: Allows players to use the /delhome command.
    default: true
  nestedhomes.list:
    description: Allows players to use the /homes command.
    default: true
  nestedhomes.share:
    description: Allows players to use the /sharehome command to manage shared homes.
    default: true
  nestedwarps.admin:
    description: Allows access to admin commands like /warputil reload and /warputil info.
    default: op
  nestedwarps.crossworld:
    description: Allows players to teleport across worlds using warps.
    default: op
  nestedhomes.crossworld:
    description: Allows players to teleport across worlds using homes.
    default: op
  nestedwarps.bypass.regions:
    description: Allows players to bypass region protection when teleporting.
    default: op