# plugin.yml
name: NestedWarps
version: 1.0
main: net.Alexxiconify.warputil.NestedWarpsPlugin
api-version: 1.21 # Updated to reflect your server's primary version
authors: [YourName] # Change this to your name or server's name
description: A Minecraft plugin for nested /warp commands, allowing "folders" for warps.

# IMPORTANT: The 'commands' section has been removed as per PaperMC's requirements for modern plugins.
# Commands are now registered programmatically in the NestedWarpsPlugin.java file.

permissions:
  nestedwarps.warp:
    description: Allows players to use the /warp command generally.
    default: true
  nestedwarps.warp.*: # Specific warp permission wildcard
    description: Allows players to warp to any specific warp.
    default: op # Or 'false' if you want to grant specific warps only
  nestedwarps.setwarp:
    description: Allows players to use the /setwarp command.
    default: op # Only server operators can set warps by default
  nestedwarps.delwarp:
    description: Allows players to use the /delwarp command.
    default: op # Only server operators can delete warps by default
  nestedwarps.list:
    description: Allows players to use the /warps command.
    default: true